Customer/Controllers/ReportController.cs
using Customer.ActionFilters;
using Customer.Models;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using System.IO;
using System.Web.Mvc;

namespace Customer.Controllers
{
    [Shared]
    public class ReportController : Controller
    {
        private v_rpt1Repository rptRepository = RepositoryHelper.Getv_rpt1Repository();
        // GET: /Report/
        public ActionResult Index()
        {
            return View(this.rptRepository.All());
        }

        [HttpPost]
        public ActionResult ExportExcel()
        {
            var data = this.rptRepository.All();
            string path = Server.MapPath("~/Templates/客戶資訊.xlsx");
            FileStream stream = new FileStream(path, FileMode.Open, FileAccess.Read);
            IWorkbook wb = new XSSFWorkbook(stream);
            stream.Close();
            ISheet sheet = wb.GetSheetAt(0);
            ICellStyle cs = sheet.GetRow(1).Cells[0].CellStyle;
            int Index = 1;
            foreach (var item in data)
            {
                IRow row = sheet.CreateRow(Index);
                CreateCell(item.客戶名稱, row, 0, cs);
                CreateCell(item.聯絡人數量.ToString(), row, 1, cs);
                CreateCell(item.客戶帳戶數量.ToString(), row, 2, cs);
                Index++;
            }
            string serverPath = @"D:/repot.xlsx";
            using (FileStream file = new FileStream(serverPath, FileMode.Create))
            {
                wb.Write(file);
                file.Close();
            }
            return File(serverPath, "application/excel","Report.xlsx");
        }

        private static void CreateCell(string value, IRow row, int index, ICellStyle cellStyle)
        {
            ICell cell = row.CreateCell(index);
            cell.SetCellValue(value);
            cell.CellStyle = cellStyle;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this.rptRepository.UnitOfWork.Context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Customer/Views/Report/Index.cshtml
@model IEnumerable<Customer.Models.v_rpt1>

@{
    ViewBag.Title = "報表";
}

<h2>@ViewBag.Title</h2>
@using (Html.BeginForm("ExportExcel", "Report", FormMethod.Post))
{
    <div class="form-group">
        <div class="col-md-2 col-centered text-center">
            <input type="submit" value="匯出Excel" class="btn btn-default" />
        </div>
    </div>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.聯絡人數量)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.客戶帳戶數量)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.客戶名稱)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.聯絡人數量)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.客戶帳戶數量)
            </td>
        </tr>
    }

</table>