Customer/Models/ViewModel/ContactViewModel.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Customer.Models.ViewModel
{
    public class ContactViewModel
    {
        public IPagedList<客戶聯絡人> Contacts { get; set; }
        public IQueryable<客戶資料> Customers { get; set; }

        public int PageIndex { get; set; }

        public ContactViewModel()
        {
            this.PageIndex = 1;
        }
    }
}

Customer/Controllers/ContactsController.cs
using Customer.ActionFilters;
using Customer.Models;
using Customer.Models.ViewModel;
using System.Data.Entity;
using System.Net;
using System.Web.Mvc;

namespace Customer.Controllers
{
    [Shared]
    public class ContactsController : Controller
    {
        private 客戶聯絡人Repository contactRepository = RepositoryHelper.Get客戶聯絡人Repository();
        private 客戶資料Repository customerRepository = RepositoryHelper.Get客戶資料Repository();
        private int pageNum = 10;
        // GET: /Contacts/
        public ActionResult Index(ContactViewModel model)
        {
            model.Contacts = this.contactRepository.PagedToList(model.PageIndex, pageNum);
            model.Customers = this.customerRepository.All();
            return View(model);
        }

        // GET: /Contacts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶聯絡人 客戶聯絡人 = this.contactRepository.Find(id.Value);
            if (客戶聯絡人 == null)
            {
                return HttpNotFound();
            }
            return View(客戶聯絡人);
        }

        // GET: /Contacts/Create
        public ActionResult Create()
        {
            ViewBag.客戶Id = new SelectList(this.customerRepository.All(), "Id", "客戶名稱");
            return View();
        }

        // POST: /Contacts/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,客戶Id,職稱,姓名,Email,手機,電話")] 客戶聯絡人 客戶聯絡人)
        {
            if (ModelState.IsValid)
            {
                this.contactRepository.Add(客戶聯絡人);
                this.contactRepository.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }

            ViewBag.客戶Id = new SelectList(this.customerRepository.All(), "Id", "客戶名稱", 客戶聯絡人.客戶Id);
            return View(客戶聯絡人);
        }

        // GET: /Contacts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶聯絡人 客戶聯絡人 = this.contactRepository.Find(id.Value);
            if (客戶聯絡人 == null)
            {
                return HttpNotFound();
            }
            ViewBag.客戶Id = new SelectList(this.customerRepository.All(), "Id", "客戶名稱", 客戶聯絡人.客戶Id);
            return View(客戶聯絡人);
        }

        // POST: /Contacts/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,客戶Id,職稱,姓名,Email,手機,電話")] 客戶聯絡人 客戶聯絡人)
        {
            if (ModelState.IsValid)
            {
                this.contactRepository.UnitOfWork.Context.Entry(客戶聯絡人).State = System.Data.Entity.EntityState.Modified;
                this.contactRepository.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }
            ViewBag.客戶Id = new SelectList(this.customerRepository.All(), "Id", "客戶名稱", 客戶聯絡人.客戶Id);
            return View(客戶聯絡人);
        }

        [HttpPost]
        public ActionResult Update(客戶聯絡人[] Contacts, int PageIndex)
        {
            if (ModelState.IsValid)
            {
                foreach (客戶聯絡人 data in Contacts)
                {
                    if (!data.IsDelete)
                    {
                        data.IsDelete = false;
                        }
                    else
                    {
                        data.是否已刪除 = !data.是否已刪除;
                    }
                    this.contactRepository.UnitOfWork.Context.Entry(data).State = EntityState.Modified;
                }
                this.contactRepository.UnitOfWork.Commit();
                return RedirectToAction("Index", new { PageIndex });
            }
            else
            {
                ContactViewModel model = new ContactViewModel();
                model.PageIndex = PageIndex;
                model.Contacts = this.contactRepository.PagedToList(PageIndex, pageNum);
                model.Customers = this.customerRepository.All();
                return View("Index", model);
            }
        }
        // GET: /Contacts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶聯絡人 客戶聯絡人 = this.contactRepository.Find(id.Value);
            if (客戶聯絡人 == null)
            {
                return HttpNotFound();
            }
            return View(客戶聯絡人);
        }

        // POST: /Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            客戶聯絡人 客戶聯絡人 = this.contactRepository.Find(id);
            this.contactRepository.Delete(客戶聯絡人);
            this.contactRepository.UnitOfWork.Commit();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this.contactRepository.UnitOfWork.Context.Dispose();
                this.customerRepository.UnitOfWork.Context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Customer/Views/Contacts/Create.cshtml
@model Customer.Models.客戶聯絡人

@{
    ViewBag.Title = "建立";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶聯絡人</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id,  new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", string.Empty)
                @Html.ValidationMessageFor(model => model.客戶Id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.職稱, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.職稱)
                @Html.ValidationMessageFor(model => model.職稱)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.姓名, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.姓名)
                @Html.ValidationMessageFor(model => model.姓名)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.手機, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.手機)
                @Html.ValidationMessageFor(model => model.手機)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話)
                @Html.ValidationMessageFor(model => model.電話)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新增" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回到列表", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Customer/Views/Contacts/Delete.cshtml
@model Customer.Models.客戶聯絡人

@{
    ViewBag.Title = "刪除";
}

<h2>@ViewBag.Title</h2>

<h3>你確定要刪除該筆紀錄?</h3>
<div>
    <h4>客戶聯絡人</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.職稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.職稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.姓名)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.姓名)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.手機)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.手機)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="刪除" class="btn btn-default" /> |
            @Html.ActionLink("回到列表", "Index")
        </div>
    }
</div>

Customer/Views/Contacts/Details.cshtml
@model Customer.Models.客戶聯絡人

@{
    ViewBag.Title = "詳細資訊";
}

<h2>Details</h2>

<div>
    <h4>客戶聯絡人</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.職稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.職稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.姓名)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.姓名)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.手機)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.手機)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("編輯", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("回到列表", "Index")
</p>

Customer/Views/Contacts/Edit.cshtml
@model Customer.Models.客戶聯絡人

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶聯絡人</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id,  new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", string.Empty)
                @Html.ValidationMessageFor(model => model.客戶Id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.職稱, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.職稱)
                @Html.ValidationMessageFor(model => model.職稱)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.姓名, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.姓名)
                @Html.ValidationMessageFor(model => model.姓名)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.手機, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.手機)
                @Html.ValidationMessageFor(model => model.手機)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話)
                @Html.ValidationMessageFor(model => model.電話)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="儲存" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回到列表", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Customer/Views/Contacts/Index.cshtml
@model Customer.Models.ViewModel.ContactViewModel

@{
    ViewBag.Title = "客戶聯絡人列表";
}

<h2>@ViewBag.Title </h2>

<p>
    @Html.ActionLink("新增", "Create")
</p>
@using (Html.BeginForm("Update", "Contacts", new { Model.PageIndex }, FormMethod.Post))
{
    <div class="form-group">
        <div class="col-md-2 col-centered text-center">
            <input type="submit" value="批次更新" class="btn btn-default" />
        </div>
    </div>
    <table class="table">
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.Contacts.First().職稱)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contacts.First().姓名)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contacts.First().Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contacts.First().手機)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contacts.First().電話)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contacts.First().客戶資料.客戶名稱)
            </th>
            <th></th>
        </tr>
        @for (int i = 0; i < Model.Contacts.Count; i++)
        {
            var item = Model.Contacts[i];
            <tr>
                <td>
                    @Html.CheckBoxFor(modelItem => Model.Contacts[i].IsDelete)
                </td>
                <td>
                    @Html.EditorFor(modelItem => Model.Contacts[i].職稱)
                </td>
                <td>
                    @Html.EditorFor(modelItem => Model.Contacts[i].姓名)
                </td>
                <td>
                    @Html.EditorFor(modelItem => Model.Contacts[i].Email)
                </td>
                <td>
                    @Html.EditorFor(modelItem => Model.Contacts[i].手機)
                </td>
                <td>
                    @Html.EditorFor(modelItem => Model.Contacts[i].電話)
                </td>
                <td>
                    @Html.DropDownListFor(modelItem => Model.Contacts[i].客戶Id, new SelectList(Model.Customers, "Id", "客戶名稱", Model.Contacts[i].客戶Id))
                </td>
                <td>
                    @Html.HiddenFor(modelItem => Model.Contacts[i].Id)
                    @Html.ActionLink("編輯", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("詳細資訊", "Details", new { id = item.Id }) |
                    @Html.ActionLink("刪除", "Delete", new { id = item.Id })
                </td>
            </tr>
        }


    </table>
}
<div class="pager">
    @Html.PagedListPager(Model.Contacts, PageIndex => Url.Action("Index", new { PageIndex }))
</div>