Customer/Models/ViewModel/BankViewModel.cs
using Customer.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Customer.Models.ViewModel
{
    public class BankViewModel
    {
        public IPagedList<客戶銀行資訊> Banks { get; set; }

        public IQueryable<客戶資料> Customers { get; set; }

        public int PageIndex { get; set; }

        public BankViewModel()
        {
            this.PageIndex = 1;
        }

    }
}

Customer/Controllers/BanksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Customer.Models;
using Customer.Models.ViewModel;
using Customer.ActionFilters;

namespace Customer.Controllers
{
    [Shared]
    public class BanksController : Controller
    {
        private 客戶銀行資訊Repository bankRepository = RepositoryHelper.Get客戶銀行資訊Repository();
        private 客戶資料Repository customerRepository = RepositoryHelper.Get客戶資料Repository();
        private int pageNum = 10;
        // GET: /Banks/
        public ActionResult Index(BankViewModel model)
        {
            model.Banks = this.bankRepository.PagedToList(model.PageIndex, pageNum);
            model.Customers = this.customerRepository.All();
            return View(model);
        }

        // GET: /Banks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶銀行資訊 客戶銀行資訊 = this.bankRepository.Find(id.Value);
            if (客戶銀行資訊 == null)
            {
                return HttpNotFound();
            }
            return View(客戶銀行資訊);
        }

        // GET: /Banks/Create
        public ActionResult Create()
        {
            ViewBag.客戶Id = new SelectList(this.customerRepository.All(), "Id", "客戶名稱");
            return View();
        }

        // POST: /Banks/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,客戶Id,銀行名稱,銀行代碼,分行代碼,帳戶名稱,帳戶號碼")] 客戶銀行資訊 客戶銀行資訊)
        {
            if (ModelState.IsValid)
            {
                this.bankRepository.Add(客戶銀行資訊);
                this.bankRepository.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }
            ViewBag.客戶Id = new SelectList(this.customerRepository.All(), "Id", "客戶名稱", 客戶銀行資訊.客戶Id);
            return View(客戶銀行資訊);
        }

        // GET: /Banks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            客戶銀行資訊 客戶銀行資訊 = this.bankRepository.Find(id.Value);
            if (客戶銀行資訊 == null)
            {
                return HttpNotFound();
            }
            ViewBag.客戶Id = new SelectList(this.customerRepository.All(), "Id", "客戶名稱", 客戶銀行資訊.客戶Id);
            return View(客戶銀行資訊);
        }

        // POST: /Banks/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,客戶Id,銀行名稱,銀行代碼,分行代碼,帳戶名稱,帳戶號碼")] 客戶銀行資訊 客戶銀行資訊)
        {
            if (ModelState.IsValid)
            {
                this.bankRepository.UnitOfWork.Context.Entry(客戶銀行資訊).State = System.Data.Entity.EntityState.Modified;
                this.bankRepository.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }
            ViewBag.客戶Id = new SelectList(this.customerRepository.All(), "Id", "客戶名稱", 客戶銀行資訊.客戶Id);
            return View(客戶銀行資訊);
        }

        [HttpPost]
        public ActionResult Update(客戶銀行資訊[] Banks, int PageIndex)
        {
            if (ModelState.IsValid)
            {
                foreach (客戶銀行資訊 data in Banks)
                {
                    if (!data.IsDelete)
                    {
                        data.IsDelete = false;
                    }
                    else
                    {
                        data.是否已刪除 = !data.是否已刪除;
                    }
                    this.bankRepository.UnitOfWork.Context.Entry(data).State = EntityState.Modified;
                }
                this.bankRepository.UnitOfWork.Commit();
                return RedirectToAction("Index", new { PageIndex });
            }
            else
            {
                BankViewModel model = new BankViewModel();
                model.PageIndex = PageIndex;
                model.Banks = this.bankRepository.PagedToList(PageIndex, pageNum);
                model.Customers = this.customerRepository.All();
                return View("Index", model);
            }
        }

        // GET: /Banks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶銀行資訊 客戶銀行資訊 = this.bankRepository.Find(id.Value);
            if (客戶銀行資訊 == null)
            {
                return HttpNotFound();
            }
            return View(客戶銀行資訊);
        }

        // POST: /Banks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            客戶銀行資訊 客戶銀行資訊 = this.bankRepository.Find(id);
            this.bankRepository.Delete(客戶銀行資訊);
            this.bankRepository.UnitOfWork.Commit();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this.customerRepository.UnitOfWork.Context.Dispose();
                this.bankRepository.UnitOfWork.Context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Customer/Views/Banks/Create.cshtml
@model Customer.Models.客戶銀行資訊

@{
    ViewBag.Title = "新增";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶銀行資訊</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id,  new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", string.Empty)
                @Html.ValidationMessageFor(model => model.客戶Id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行名稱, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行名稱)
                @Html.ValidationMessageFor(model => model.銀行名稱)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行代碼, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行代碼)
                @Html.ValidationMessageFor(model => model.銀行代碼)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.分行代碼, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.分行代碼)
                @Html.ValidationMessageFor(model => model.分行代碼)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶名稱, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶名稱)
                @Html.ValidationMessageFor(model => model.帳戶名稱)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶號碼, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶號碼)
                @Html.ValidationMessageFor(model => model.帳戶號碼)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新增" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回到列表", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Customer/Views/Banks/Delete.cshtml
@model Customer.Models.客戶銀行資訊

@{
    ViewBag.Title = "刪除";
}

<h2>@ViewBag.Title</h2>

<h3>你確定要刪除該筆紀錄?</h3>
<div>
    <h4>客戶銀行資訊</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.銀行名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.銀行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.分行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.分行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶號碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶號碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="刪除" class="btn btn-default" /> |
            @Html.ActionLink("回到列表", "Index")
        </div>
    }
</div>

Customer/Views/Banks/Details.cshtml
@model Customer.Models.客戶銀行資訊

@{
    ViewBag.Title = "詳細資訊";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>客戶銀行資訊</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.銀行名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.銀行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.分行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.分行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶號碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶號碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("編輯", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("回到列表", "Index")
</p>

Customer/Views/Banks/Edit.cshtml
@model Customer.Models.客戶銀行資訊

@{
    ViewBag.Title = "編輯";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶銀行資訊</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id,  new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", string.Empty)
                @Html.ValidationMessageFor(model => model.客戶Id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行名稱, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行名稱)
                @Html.ValidationMessageFor(model => model.銀行名稱)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行代碼, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行代碼)
                @Html.ValidationMessageFor(model => model.銀行代碼)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.分行代碼, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.分行代碼)
                @Html.ValidationMessageFor(model => model.分行代碼)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶名稱, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶名稱)
                @Html.ValidationMessageFor(model => model.帳戶名稱)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶號碼, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶號碼)
                @Html.ValidationMessageFor(model => model.帳戶號碼)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="儲存" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回到列表", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Customer/Views/Banks/Index.cshtml
@model Customer.Models.ViewModel.BankViewModel

@{
    ViewBag.Title = "客戶銀行列表";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("新增", "Create")
</p>
@using (Html.BeginForm("Update", "Banks", new { Model.PageIndex }, FormMethod.Post))
{
    <div class="form-group">
        <div class="col-md-2 col-centered text-center">
            <input type="submit" value="批次更新" class="btn btn-default" />
        </div>
    </div>
    <table class="table">
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.Banks.First().銀行名稱)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Banks.First().銀行代碼)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Banks.First().分行代碼)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Banks.First().帳戶名稱)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Banks.First().帳戶號碼)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Banks.First().客戶資料.客戶名稱)
            </th>
            <th></th>
        </tr>
        @for (int i = 0; i < Model.Banks.Count; i++)
        {
            var item = Model.Banks[i];
            <tr>
                <td>
                    @Html.CheckBoxFor(modelItem => Model.Banks[i].IsDelete)
                </td>
                <td>
                    @Html.EditorFor(modelItem => Model.Banks[i].銀行名稱)
                </td>
                <td>
                    @Html.EditorFor(modelItem => Model.Banks[i].銀行代碼)
                </td>
                <td>
                    @Html.EditorFor(modelItem => Model.Banks[i].分行代碼)
                </td>
                <td>
                    @Html.EditorFor(modelItem => Model.Banks[i].帳戶名稱)
                </td>
                <td>
                    @Html.EditorFor(modelItem => Model.Banks[i].帳戶號碼)
                </td>
                <td>
                    @Html.DropDownListFor(modelItem => Model.Banks[i].客戶Id, new SelectList(Model.Customers, "Id", "客戶名稱", Model.Banks[i].客戶Id))
                </td>
                <td>
                    @Html.HiddenFor(modelItem => Model.Banks[i].Id)
                    @Html.ActionLink("編輯", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("詳細資訊", "Details", new { id = item.Id }) |
                    @Html.ActionLink("刪除", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
}
<div class="pager">
    @Html.PagedListPager(Model.Banks, PageIndex => Url.Action("Index", new { PageIndex }))
</div>