Customer/Models/ViewModel/CustomerViewModel.cs
using PagedList;
namespace Customer.Models.ViewModel
{
    public class CustomerViewModel
    {
        public IPagedList<客戶資料> Customers { get; set; }
        public int PageIndex { get; set; }

        public CustomerViewModel()
        {
            this.PageIndex = 1;
        }
    }
}

Customer/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Customer.Models;
using Customer.Models.ViewModel;
using Customer.ActionFilters;

namespace Customer.Controllers
{
    [Shared]
    public class CustomersController : Controller
    {
        private 客戶資料Repository customerRepository = RepositoryHelper.Get客戶資料Repository();
        private int pageNum = 10;
        // GET: /Customers/
        public ActionResult Index(CustomerViewModel model)
        {
            model.Customers = this.customerRepository.PagedToList(model.PageIndex, pageNum);
            return View(model);
        }

        // GET: /Customers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶資料 客戶資料 = this.customerRepository.Find(id.Value);
            if (客戶資料 == null)
            {
                return HttpNotFound();
            }
            return View(客戶資料);
        }

        // GET: /Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Customers/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,客戶名稱,統一編號,電話,傳真,地址,Email")] 客戶資料 客戶資料)
        {
            if (ModelState.IsValid)
            {
                this.customerRepository.Add(客戶資料);
                this.customerRepository.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }

            return View(客戶資料);
        }

        // GET: /Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶資料 客戶資料 = this.customerRepository.Find(id.Value);
            if (客戶資料 == null)
            {
                return HttpNotFound();
            }
            return View(客戶資料);
        }

        // POST: /Customers/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,客戶名稱,統一編號,電話,傳真,地址,Email")] 客戶資料 客戶資料)
        {
            if (ModelState.IsValid)
            {
                this.customerRepository.UnitOfWork.Context.Entry(客戶資料).State = EntityState.Modified;
                this.customerRepository.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }
            return View(客戶資料);
        }

        [HttpPost]
        public ActionResult Update(客戶資料[] Customers, int PageIndex)
        {
            if (ModelState.IsValid)
            {
                foreach (客戶資料 data in Customers)
                {
                    if (!data.IsDelete)
                    {
                        data.IsDelete = false;
                    }
                    else
                    {
                        data.是否已刪除 = !data.是否已刪除;
                    }
                    this.customerRepository.UnitOfWork.Context.Entry(data).State = EntityState.Modified;
                }
                this.customerRepository.UnitOfWork.Commit();
                return RedirectToAction("Index", new { PageIndex });
            }
            else
            {
                CustomerViewModel model = new CustomerViewModel();
                model.PageIndex = PageIndex;
                model.Customers = this.customerRepository.PagedToList(PageIndex, pageNum);
                return View("Index", model);
            }
        }

        // GET: /Customers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶資料 客戶資料 = this.customerRepository.Find(id.Value);
            if (客戶資料 == null)
            {
                return HttpNotFound();
            }
            return View(客戶資料);
        }

        // POST: /Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            客戶資料 客戶資料 = this.customerRepository.Find(id.Value);

            this.customerRepository.Delete(客戶資料);
            this.customerRepository.UnitOfWork.Commit();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this.customerRepository.UnitOfWork.Context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Customer/Views/Customers/Create.cshtml
@model Customer.Models.客戶資料

@{
    ViewBag.Title = "新增";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶資料</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶名稱, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.客戶名稱)
                @Html.ValidationMessageFor(model => model.客戶名稱)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.統一編號, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.統一編號)
                @Html.ValidationMessageFor(model => model.統一編號)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話)
                @Html.ValidationMessageFor(model => model.電話)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.傳真, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.傳真)
                @Html.ValidationMessageFor(model => model.傳真)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.地址, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.地址)
                @Html.ValidationMessageFor(model => model.地址)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新增" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回到列表", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Customer/Views/Customers/Delete.cshtml
@model Customer.Models.客戶資料

@{
    ViewBag.Title = "刪除";
}

<h2>@ViewBag.Title</h2>

<h3>你確定要刪除該筆紀錄?</h3>
<div>
    <h4>客戶資料</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.統一編號)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.統一編號)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.傳真)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.傳真)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.地址)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.地址)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="刪除" class="btn btn-default" /> |
            @Html.ActionLink("回到列表", "Index")
        </div>
    }
</div>

Customer/Views/Customers/Details.cshtml
@model Customer.Models.客戶資料

@{
    ViewBag.Title = "詳細資訊";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>客戶資料</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.統一編號)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.統一編號)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.傳真)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.傳真)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.地址)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.地址)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("編輯", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("回到列表", "Index")
</p>

Customer/Views/Customers/Edit.cshtml
@model Customer.Models.客戶資料

@{
    ViewBag.Title = "修改";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶資料</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶名稱, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.客戶名稱)
                @Html.ValidationMessageFor(model => model.客戶名稱)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.統一編號, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.統一編號)
                @Html.ValidationMessageFor(model => model.統一編號)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話)
                @Html.ValidationMessageFor(model => model.電話)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.傳真, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.傳真)
                @Html.ValidationMessageFor(model => model.傳真)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.地址, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.地址)
                @Html.ValidationMessageFor(model => model.地址)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="儲存" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回到列表", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Customer/Views/Customers/Index.cshtml
@model Customer.Models.ViewModel.CustomerViewModel

@{
    ViewBag.Title = "客戶列表";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("新增", "Create")
</p>

@using (Html.BeginForm("Update", "Customers", new { Model.PageIndex }, FormMethod.Post))
{
    <div class="form-group">
        <div class="col-md-2 col-centered text-center">
            <input type="submit" value="批次更新" class="btn btn-default" />
        </div>
    </div>
    <table class="table">
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.Customers.First().客戶名稱)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customers.First().統一編號)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customers.First().電話)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customers.First().傳真)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customers.First().地址)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customers.First().Email)
            </th>
            <th></th>
        </tr>

        @for (int i = 0; i < Model.Customers.Count; i++)
        {
            var item = Model.Customers[i];
            <tr>
                <td>
                    @Html.CheckBoxFor(modelItem => Model.Customers[i].IsDelete)
                </td>
                <td>
                    @Html.EditorFor(modelItem => Model.Customers[i].客戶名稱)
                </td>
                <td>
                    @Html.EditorFor(modelItem => Model.Customers[i].統一編號)
                </td>
                <td>
                    @Html.EditorFor(modelItem => Model.Customers[i].電話)
                </td>
                <td>
                    @Html.EditorFor(modelItem => Model.Customers[i].傳真)
                </td>
                <td>
                    @Html.EditorFor(modelItem => Model.Customers[i].地址)
                </td>
                <td>
                    @Html.EditorFor(modelItem => Model.Customers[i].Email)
                </td>
                <td>
                    @Html.HiddenFor(modelItem => Model.Customers[i].Id)
                    @Html.ActionLink("編輯", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("詳細資訊", "Details", new { id = item.Id }) |
                    @Html.ActionLink("刪除", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
}
<div class="pager">
    @Html.PagedListPager(Model.Customers, PageIndex => Url.Action("Index", new { PageIndex }))
</div>